name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: test env
      run: echo My name is $NAME

    - shell: bash
      run: |
        expr $VAR_1 + $VAR_2 > math-homework.txt
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.FILE }}
        path: math-${{ env.FILE }}.txt
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
        name: homework
    - shell: bash
      run: |
        value=`cat $FILE/math-$FILE.txt`
        echo The result is $value

    env:
      NAME: Ankur
      VAR_1: 10
      VAR_2: 90
      FILE: homework

  static:
    runs-on: ubuntu-latest

    steps:
    - name: test static env Branch
      run: echo ${GITHUB_REF}
    - name: test static env test3
      run: echo ${GITHUB_ACTOR}
    - name: test date
      run: echo $(date +%s)
    - name: install jq
      run: sudo apt-get install jq
    - name: create json config
      run: |
        jq -n --arg author "${GITHUB_ACTOR}" --arg branch "${GITHUB_REF##*/}" --arg date "$(date +%s)" '{author:$author, branch:$branch, date:$date}' > config.json
        ls
